### ISSUE TITLE
[ISSUE] Pod has unbound immediate...

### ISSUE THREAD

**Issue by KarenKawaii** [jswidler/elasticsearch-kubed#6]
**OS: Centos7**
**Config for .yaml files:**
![image](https://user-images.githubusercontent.com/11741384/55602169-86e1e800-5721-11e9-8f6c-6844d7d480f9.png)

Hi

I was reading and recreating the installation in your blog for ELK and when I execute:
![image](https://user-images.githubusercontent.com/11741384/55601975-aa586300-5720-11e9-9f37-c48641d20a2c.png)

The following error is showed:

![image](https://user-images.githubusercontent.com/11741384/55601946-8a28a400-5720-11e9-99d7-b35c38720b5c.png)

I have checked my volume and it is in pending state.
![image](https://user-images.githubusercontent.com/11741384/55602211-bd1f6780-5721-11e9-8f9c-818bab4398d6.png)

Why is this happening?
How can I know the reason why the volume claim is pending?

I would appreciate any comments about it to guide me in finding the solution.

Regards.

**Comment by jswidler** [comment]
I see you are using the ssd class - this is used with either GKE or AWS.  If you are using something else, you need to figure out how to configure the storage class a different way, or you can switch back to the default every cluster has called `standard`.

**Comment by NFhbar** [comment]
To follow up on this, it seems the pod cannot be scheduled due to the persistent volume claim never leaving the `Pending` status:

<img width="1157" alt="Screen Shot 2019-05-01 at 6 06 39 PM" src="https://user-images.githubusercontent.com/23327624/57052450-15bc2480-6c3c-11e9-998f-993582eacdeb.png">

<img width="1473" alt="Screen Shot 2019-05-01 at 6 06 54 PM" src="https://user-images.githubusercontent.com/23327624/57052455-1c4a9c00-6c3c-11e9-92e5-5f2e9df9e588.png">

Configuration:
```
Enter a kubernetes namespace for the elasticsearch cluster (default='default'): elk
Enter a name for the elasticsearch cluster (default='my-es-cluster'): charge-es-cluster
Select the node size: 
1: minikube
2: 4cpu X N
3: 8cpu X N
4: 16cpu X N
[1-4]:  (default='2'): 2
Enter the number of nodes (2-9) (default='2'): 2
Enter the data volume size in GB [10-9999] (default='250'): 250
```

Any ideas?

UPDATE:

This issue was caused by not specifying the volume type to SSD instead of standard during cluster creation.
