### ISSUE TITLE
Direct connect to elastic-master

### ISSUE THREAD

**Issue by rjluzardo** [jswidler/elasticsearch-kubed#9]
Thanks a lot for the guide, very useful. I am very new with K8s and I am getting some grief from the elastic team about the fact that they can’t connect directly to the elasticsearch-master servers to import data as they do on a regular physical/virtual host architecture. I have not found a way to expose that headless service. Can anyone think on any way I can expose the elasticsearch server as we do the kibana and logstash, or if think on any way of doing that without exposing elasticsearch-master I am all ears.

Thanks in advance

**Comment by jswidler** [comment]
ES was insecure by default so I didn't have a good answer before.  But with ES 7.1, it has authentication out of the box.  So hopefully using the new version of ES will make this easier, since you can just use a kubernetes service to expose ES directly.  Note that when I am writing this comment, elasticsearch-kubed (this repo) has not been updated to 7.1 yet.
